### ISSUE TITLE
Wrong invariant-ekf-master version?

### ISSUE THREAD

**Issue by overevil** [UMich-CURLY/invariant-ekf-ros-new#1]
Thanks for the great works
Im encoutering this problem when I build the project. I want to know how to fix it.Hope for reply
![image](https://user-images.githubusercontent.com/71376808/113073638-0cf37500-91fc-11eb-97e6-2d16ab39ee41.png)

![image](https://user-images.githubusercontent.com/71376808/113073606-fbaa6880-91fb-11eb-983d-14c09fac89e6.png)

**Comment by zeroAska** [comment]
Which branch of invariant-ekf (not ros) are you using? have you tried the devel branch

**Comment by overevil** [comment]
Devel branch can be sucessfully. Thank you very much.
